SELECT TOP (1000) [ServerName]
      ,[Monitored]
      ,[ValidFrom]
      ,[ValidTo]
  FROM [SQLDataQualityMonitor].[dbo].[Servers]
  
  SELECT TOP (1000) [ServerName]
      ,[name]
      ,[create_date]
      ,[collation_name]
      ,[user_access_desc]
      ,[state_desc]
      ,[recovery_model_desc]
      ,[ValidFrom]
      ,[ValidTo]
  FROM [SQLDataQualityMonitor].[dbo].[Databases]